server.port=8080
client.url=http://stat-server:9090

spring.datasource.url=jdbc:postgresql://ewm-main-db:5432/ewm-main
spring.datasource.username=main
spring.datasource.password=main
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

logging.level.ru.practicum.main.service=DEBUG
logging.level.ru.practicum.stat.client=DEBUG
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE