services:
  stat-server:
    build: stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stat-server-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      timeout: 5s
      interval: 5s
      retries: 10

  stat-server-db:
    image: postgres:16.1
    container_name: stat-server-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      stat-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      timeout: 5s
      interval: 5s
      retries: 10

#  ewm-db:
#    image: postgres:16.1
